### PR TITLE
deprecate macZip

### PR DESCRIPTION
**Pull request by firsara**

### CODE REVIEW

**Comment by eridal** [comment]
I think this is duplicate of #145

I'm waiting for the feature, so I'm OK with any PR getting merged :wink:

**Comment by firsara** [comment]
Well afaik it's already been implemented in the latest 2.20 release. 
And actually I couldn't even get the grunt task to work with multiple platforms without my change, seems broken at the moment...

**Comment by eridal** [comment]
Yes, can confirm. We are building using a similar workaround.

Hope this gets fixed soonish.

**Comment by dennisroche** [comment]
Any chance we could get this merged? It is preventing optimising the start-up of the windows apps.

Grunt/Gulp tasks lagging behind the tool being wrapped is the reason why I've personally moved to using npm scripts.

**Comment by gpetrov** [comment]
I wonder why such simple fix isn't merged yet and breaks the new zip option already for 7+ months...

**Comment by adam-lynch** [comment]
Sorry for taking so long to get to this. Thanks for the PR. Can you please confirm that with this change someone can still use `macZip` or `zip`?

P.S. If you'd like to help out this project, see  #154.

**Comment by gpetrov** [comment]
yes the new nw-builder has its own zip option now, so here in the grunt-nw-builder, by fixing the deprecated macZip - you are actually suppressing the native option. So this patch fixes it as it should.

**Comment by adam-lynch** [comment]
Thanks!

**Comment by firsara** [comment]
@adam-lynch thanks for merging! I'll be thinking about Maintaining the project, thinking about moving to electron myself as I feel that nwjs development kind of froze a bit :/

**Comment by gpetrov** [comment]
@firsara actually nwjs has being very active for the last 6 months, they have caught up very fast and are now running along with the latest chrome builds! They also have all the chrome apps API built-in!

check the activity graph: https://github.com/nwjs/nw.js/graphs/contributors

So actually Electron is now the one running behind...

**Pull request merged**
